pool:
  vmImage: ubuntu-latest

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 't-mobile'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'kuber'
    command: 'get'
    arguments: pods
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'