# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: GitHubComment@0
  inputs:
    gitHubConnection: 'Connect to my gh'
    repositoryName: 'hlarsonhlarson/azure-sample'
    id: 'issue/2'
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'kuber'
    command: 
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    
- bash: |
    echo 1
    chmod 777 Bash.sh
    bash Bash.sh
    echo $(NOTHIDDEN100)
    echo $(HIDENOW)
    echo $(SERVCON1)
    echo $(SERVCON2)
    echo $(SERVCON3)
    echo $(TMOB)
    

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
